import Head from "next/head";
import Link from "next/link";
import About from "../components/About";
import ContactMe from "../components/ContactMe";
import Image from "next/image";
import Header from "../components/Header";
import Hero from "../components/Hero";
import Projects from "../components/Projects";
import Skills from "../components/Skills";
import WorkExperience from "../components/WorkExperience";
import { fetchPageInfo } from "../utils/fetchPageInfo";
import { fetchExperience } from "../utils/fetchExperience";
import { fetchSkills } from "../utils/fetchSkills";
import { fetchProject } from "../utils/fetchProjects";
import { fetchSocial } from "../utils/fetchSocials";

export default function Home({
  pageInfo = [],
  experience = [],
  skills = [],
  projects = [],
  socials = [],
}) {
  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#F7AB0A]/80">
      <Head>
        <title>Mamun Ahmed Modern Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://avatars.githubusercontent.com/u/66796161"
        />
      </Head>
      {/* Header */}
      <Header socials={socials} />
      {/* Hero */}
      <section id="hero" className="snap-center">
        <Hero pageInfo={pageInfo} />
      </section>

      {/* About */}
      <section id="about" className="snap-center">
        <About pageInfo={pageInfo} />
      </section>

      {/* Experience */}
      <section id="experience" className="snap-center">
        <WorkExperience experience={experience} />
        {/* <Experience />  */}
      </section>

      {/* Skills */}
      <section id="skills" className="snap-start">
        <Skills skills={skills} />
      </section>

      {/* Projects */}
      <section id="projects" className="snap-start">
        <Projects projects={projects} />
      </section>

      {/* Contact Me */}
      <section id="contact" className="snap-start">
        <ContactMe />
      </section>
      <Link href="#hero">
        <footer className="sticky bottom-5 w-full cursor-pointer">
          <div className="flex items-center justify-center">
            <Image
              className="rounded-full filter grayscale hover:grayscale-0 cursor-pointer"
              src="https://avatars.githubusercontent.com/u/66796161"
              alt="Mamun Ahmed"
              width={40}
              height={40}
            />
          </div>
        </footer>
      </Link>
    </div>
  );
}

export const getServerSideProps = async () => {
  const pageInfo = await fetchPageInfo();
  const experience = await fetchExperience();
  const skills = await fetchSkills();
  const projects = await fetchProject();
  const socials = await fetchSocial();

  return {
    props: {
      pageInfo,
      experience,
      skills,
      projects,
      socials,
    },
  };
};
